from django.urls import path
from . import views

urlpatterns = [
    # ── Auth ──────────────────────────────────────────────────────────
    path('',          views.auth_page,     name='auth'),
    path('login/',    views.login_view,    name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/',   views.logout_view,   name='logout'),
    path('api/stats/', views.site_stats_api, name='site_stats_api'),

    # ── User pages ────────────────────────────────────────────────────
    path('home/',              views.home,              name='home'),
    path('categories/',        views.categories_page,   name='categories'),
    path('authors/',           views.authors_page,      name='authors'),
    path('category/<slug:slug>/', views.category_books, name='category_books'),
    path('search/',            views.search_view,       name='search'),
    path('community/',              views.community,            name='community'),
    path('community/new/',          views.create_post,          name='create_post'),
    path('community/like/<int:pk>/', views.like_post,           name='like_post'),
    path('community/comment/<int:post_pk>/', views.add_post_comment, name='add_post_comment'),    path('community/comment/<int:pk>/like/', views.like_post_comment, name='like_post_comment'),    path('community/post/<int:pk>/delete/', views.delete_post,       name='delete_post'),
    path('community/comment/<int:pk>/delete/', views.delete_comment, name='delete_comment'),
    path('quotes/like/<int:pk>/', views.like_quote, name='like_quote'),
    path('reviews/like/<int:pk>/', views.like_review, name='like_review'),
    path('quotes/<int:pk>/delete/', views.delete_quote, name='delete_quote'),
    path('reviews/<int:pk>/delete/', views.delete_review, name='delete_review'),
    path('quotes/',                 views.quotes_page,          name='quotes'),
    path('reviews/',           views.reviews_page,      name='reviews_page'),

    path('my-library/',        views.my_library,        name='my_library'),
    path('profile/',           views.profile,           name='profile'),
    path('user/<str:username>/', views.user_profile,    name='user_profile'),
    path('user/<str:username>/follow/', views.follow_user, name='follow_user'),
    path('api/followers/<str:username>/', views.followers_api, name='followers_api'),
    path('api/following/<str:username>/', views.following_api, name='following_api'),
    path('settings/',          views.settings_page,     name='settings'),
    path('change-password/',   views.change_password,   name='change_password'),
    path('upload/',            views.upload_book,       name='upload_book'),
    path('author/<int:pk>/',   views.author_detail,     name='author_detail'),
    path('recommendations/',   views.recommendations_view, name='recommendations'),

    # ── Book detail & actions ─────────────────────────────────────────
    path('book/<slug:slug>/',            views.book_detail,   name='book_detail'),
    path('book/<slug:slug>/download/',   views.download_book, name='download_book'),
    path('book/<slug:slug>/rate/',       views.rate_book,     name='rate_book'),
    path('book/<slug:slug>/review/',     views.add_review,    name='add_review'),
    path('book/<slug:slug>/quote/',      views.add_quote,     name='add_quote'),
    path('book/<slug:slug>/like/',       views.toggle_like,   name='toggle_like'),

    # ── Admin ─────────────────────────────────────────────────────────
    path('admin-panel/',              views.admin_dashboard,        name='admin_dashboard'),
    path('admin-panel/books/',        views.admin_books,            name='admin_books'),
    path('admin-panel/books/add/',    views.admin_add_book,         name='admin_add_book'),
    path('admin-panel/books/<int:pk>/edit/',   views.admin_edit_book,        name='admin_edit_book'),
    path('admin-panel/books/<int:pk>/approve/', views.admin_approve_book, name='admin_approve_book'),
    path('admin-panel/books/<int:pk>/delete/',  views.admin_delete_book,  name='admin_delete_book'),
    path('admin-panel/categories/',   views.admin_categories,       name='admin_categories'),
    path('admin-panel/categories/add/',    views.admin_add_category,    name='admin_add_category'),
    path('admin-panel/categories/<int:pk>/delete/', views.admin_delete_category, name='admin_delete_category'),
    path('admin-panel/authors/',      views.admin_authors,          name='admin_authors'),
    path('admin-panel/authors/add/',  views.admin_add_author,       name='admin_add_author'),
    path('admin-panel/authors/<int:pk>/edit/',   views.admin_edit_author,      name='admin_edit_author'),
    path('admin-panel/authors/<int:pk>/delete/', views.admin_delete_author, name='admin_delete_author'),
    path('admin-panel/users/',        views.admin_users,            name='admin_users'),
    path('admin-panel/users/<int:pk>/ban/',    views.admin_ban_user,    name='admin_ban_user'),
    path('admin-panel/users/<int:pk>/unban/',  views.admin_unban_user,  name='admin_unban_user'),
    path('admin-panel/users/<int:pk>/delete/', views.admin_delete_user, name='admin_delete_user'),
    path('admin-panel/books/<int:pk>/preview/', views.admin_book_preview, name='admin_book_preview'),
    path('admin-panel/books/<int:pk>/comments/', views.admin_book_comments, name='admin_book_comments'),
    path('admin-panel/community/', views.admin_community, name='admin_community'),
    path('admin-panel/community/<int:pk>/delete/', views.admin_delete_post, name='admin_delete_post'),
    path('admin-panel/community/<int:pk>/comments/', views.admin_post_comments, name='admin_post_comments'),
    path('admin-panel/community/comments/<int:pk>/delete/', views.admin_delete_post_comment, name='admin_delete_post_comment'),
]
