# Generated by Django 6.0.4 on 2026-05-13 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='lib_follow_follower_following_unique',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
